version: 1
product:
  id: prod-001
  name: Zero-Scout
  owner: product-owner
  vision: A lightweight, stateless, 'Fire and Forget' market intelligence tool for
    retail investors that scrapes open web news, analyzes sentiment using deterministic
    NLP, and presents summaries, strictly adhering to zero-cost and zero-auth constraints.
  constraints:
  - Zero Auth
  - Zero Paid APIs
  - Zero Generative AI
  - Zero Infrastructure Cost
  rules:
  - Client-Side Chaining for multiple tickers
  - 2-second Throttle between requests
  - Pin backend dependencies
  requirements:
  - Next.js (Frontend)
  - Python Serverless (Backend)
  - duckduckgo-search (Data)
  - TextBlob (Sentiment)
  - Vercel Hosting
  status: active
