version: 1
product:
  id: prod-001
  name: Zero-Scout
  owner: product-owner
  vision: A lightweight, stateless, serverless market intelligence tool for retail
    investors that scrapes, analyzes, and summarizes real-time financial news without
    login or cost.
  constraints:
  - Zero Auth (Stateless)
  - Zero Paid APIs (DuckDuckGo only)
  - Zero Generative AI (Deterministic NLP)
  - Zero Infrastructure Cost (Vercel Hobby Tier)
  rules:
  - Use Client-Side Chaining to avoid timeouts
  - Implement 2-second throttle between requests
  - Pin dependencies to prevent library breakage
  requirements:
  - 'Frontend: Next.js + Tailwind CSS'
  - 'Backend: Python Serverless Functions'
  - 'Data: duckduckgo-search (time=''d'')'
  - 'Analysis: TextBlob (Sentiment) + Sumy/LSA (Summarization)'
  status: active
